version: "1.0"

services:
    db:
        image: "mariadb:bionic"
        container_name: "yggtree-rathena-db"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "yggtree-rathenadb:/var/lib/mysql" # save database to local disk
            - "../../sql-files/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok

    builder:
        profiles: ["build"]
        image: "yggtree-rathena:local"
        container_name: "yggtree-rathena-builder"
        command: "/bin/sh"
        volumes:
            - "../..:/yggtree-rathena" # mount git repo directory inside container
            - "./asset/conf:/yggtree-rathena/conf/import"   #localdev conf folder relation
            - "./asset/db:/yggtree-rathena/db/import"   #localdev db folder relation

        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            BUILDER_CONFIGURE: "--enable-packetver=20220406"

    login:
        image: "yggtree-rathena:local"
        container_name: "yggtree-rathena-login"
        command: sh -c "/bin/wait-for db:3306 -- /yggtree-rathena/login-server"
        ports:
            - "6900:6900" # login server
        volumes:
            - "../..:/yggtree-rathena" # mount git repo directory inside container
            - "./asset/conf:/yggtree-rathena/conf/import"   #localdev conf folder relation
            - "./asset/db:/yggtree-rathena/db/import"   #localdev db folder relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
    char:
        image: "yggtree-rathena:local"
        container_name: "yggtree-rathena-char"
        command: sh -c "/bin/wait-for db:3306 -- /yggtree-rathena/char-server"
        ports:
            - "6121:6121" # char server
        volumes:
            - "../..:/yggtree-rathena" # mount git repo directory inside container
            - "./asset/conf:/yggtree-rathena/conf/import"   #localdev conf folder relation
            - "./asset/db:/yggtree-rathena/db/import"   #localdev db folder relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - login
    map:
        image: "yggtree-rathena:local"
        container_name: "yggtree-rathena-map"
        command: sh -c "/bin/wait-for db:3306 -- /yggtree-rathena/map-server"
        ports:
            - "5121:5121" # map server
        volumes:
            - "../..:/yggtree-rathena" # mount git repo directory inside container
            - "./asset/conf:/yggtree-rathena/conf/import"   #localdev conf folder relation
            - "./asset/db:/yggtree-rathena/db/import"   #localdev db folder relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - char

volumes:
    yggtree-rathenadb:
        name: "yggtree-rathenadb" # Force volume name to avoid docker prepending it with 'docker_'
