version: "3.7"

services:
    db:
        image: "mariadb:bionic"
        container_name: "legacy_rathena_db"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "legacy-rathenadb:/var/lib/mysql" # save database to local disk
            - "../../sql-files/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok

    builder:
        image: "legacy-rathena:local"
        container_name: "legacy-rathena-builder"
        command: "/legacy-rathena/tools/docker/builder.sh"
        volumes:
            - "../..:/legacy-rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/legacy-rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/legacy-rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/legacy-rathena/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            BUILDER_CONFIGURE:

    login:
        image: "legacy-rathena:local"
        container_name: "legacy-rathena-login"
        command: sh -c "/bin/wait-for db:3306 -- /legacy-rathena/login-server"
        ports:
            - "6900:6900" # login server
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/legacy-rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/legacy-rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/legacy-rathena/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
    char:
        image: "legacy-rathena:local"
        container_name: "legacy-rathena-char"
        command: sh -c "/bin/wait-for db:3306 -- /legacy-rathena/char-server"
        ports:
            - "6121:6121" # char server
        volumes:
            - "../..:/legacy-rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/legacy-rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/legacy-rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/legacy-rathena/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - login
    map:
        image: "legacy-rathena:local"
        container_name: "legacy-rathena-map"
        command: sh -c "/bin/wait-for db:3306 -- /legacy-rathena/map-server"
        ports:
            - "5121:5121" # map server
        volumes:
            - "../..:/legacy-rathena" # mount git repo directory inside container
            - "./asset/inter_conf.txt:/legacy-rathena/conf/import/inter_conf.txt" # load db connection
            - "./asset/char_conf.txt:/legacy-rathena/conf/import/char_conf.txt"   #localdev login-char relation
            - "./asset/map_conf.txt:/legacy-rathena/conf/import/map_conf.txt"     #localdev char-map relation
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - char

volumes:
    legacy-rathenadb:
